baseURL = "https://cat0ftheyear.github.io/temp_title/"
theme = "PaperMod"
paginate = 5
defaultContentLanguage = "he"

[languages]
  [languages.he]
    direction = "rtl"
    label = "עברית"
    title = "הבלוג שלי"
    locale = "he"
    weight = 1

    [languages.he.params]
      author = "שם"
      description = "הבלוג האישי שלי"
      ShowReadingTime = true
      ShowPostNavLinks = true
      ShowBreadCrumbs = true
      ShowCodeCopyButtons = true
      ShowShareButtons = false

    [languages.he.params.homeInfoParams]
      Title = "שלום"
      Content = "ברוכים הבאים לבלוג שלי."

    [[languages.he.menu.main]]
      identifier = "posts"
      name = "פוסטים"
      url = "posts/"
      weight = 10

    [[languages.he.menu.main]]
      identifier = "tags"
      name = "תגיות"
      url = "tags/"
      weight = 20
